server:
  port: 7001    #浏览器输入localhost:7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称  在host文件中已经配置了eureka7001.com 就是localhost
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      # 集群7001上配7002 ，7002上配7001 相互注册
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
